name: btrfs-progs-gael
base: core22
summary: Btrfs Progs
description: |
  btrfs is a modern copy on write (CoW) filesystem for Linux aimed at implementing advanced features while also focusing on fault tolerance, repair and easy administration. Its main features and benefits are:
  * Snapshots which do not make the full copy of files
  * RAID - support for software-based RAID 0, RAID 1, RAID 10
  * Self-healing - checksums for data and metadata, automatic detection of silent data corruptions

version: 5.16.2
grade: stable 
confinement: strict

architectures:
  - build-on: amd64

license: "GPL-3.0-or-later"

layout:
  /var/lib/btrfs:                       # Needed to create btrfs sockets
    bind: $SNAP_DATA/var/lib/btrfs

apps:
  btrfs:
    command: bin/btrfs

  mkfs-btrfs:
    command: sbin/mkfs.btrfs

  btrfs-scrub:
    command: scripts/btrfs-scrub

  btrfs-snap:
    command: scripts/btrfs-snap

parts:
  utils:
    plugin: dump
    source: snap/local/utils
    organize:
      '*' : scripts/
    prime:
      - scripts/btrfs-scrub
      - scripts/btrfs-snap

  app:
    plugin: nil
    stage-packages:
      - btrfs-progs
