#!/bin/bash

VERSION="1.0"
PROG=${0##*/}

USAGE="Usage: ${PROG} -h for usage help
       ${PROG} -V for version
       ${PROG} <prefix> <count>"
SYNOPSIS="${PROG} <prefix> <count>
<prefix>     is the prefix to be used in the name of the snapshot.
             E.g. hourly, daily, weekly...
<count>      The number of snapshots with the given prefix to keep."

while getopts "hV" ARG; do
	case "${ARG}" in
		h )
			echo "$SYNOPSIS"
			exit 0
			;;
		V )
			echo "${PROG} Version ${VERSION}"
			exit 0
			;;
		* )
			echo "$USAGE"
			exit 1
			;;
	esac
done


if [ $# -ne 2 ] ; then
	echo "$USAGE"
	exit 1
fi

PREFIX=$1
COUNT=$(( $2+1 ))

DEVICE_LIST=`grep ' btrfs ' /proc/mounts | awk '{ print $1 }' | sort -u`

for DEVICE in $DEVICE_LIST
do
   MOUNT_POINT=`grep "$DEVICE" /proc/mounts | awk '{ print $2 }' | head -n 1`

   if [ ! -d "${MOUNT_POINT}/.snapshot" ]; then
      mkdir "${MOUNT_POINT}/.snapshot"
   fi

   TIMESTAMP=`date +'%Y-%m-%d_%H:%M:%S'`

   btrfs subvol snapshot -r ${MOUNT_POINT} ${MOUNT_POINT}/.snapshot/${PREFIX}_${TIMESTAMP} 2>&1

   ls -dr ${MOUNT_POINT}/.snapshot/${PREFIX}_* | tail -n +${COUNT} | while read SNAP ; do
      
      btrfs subvolume delete ${SNAP} 2>&1
   done

done
